#!/bin/bash

CC=gcc
CFLAGS="-g -Wall -lhiredis -I. -I.." 


#######################################################
## 		compile all the files from $*
##-----------------------------------------------------

compile_all_implicitly()
{
	for src in $*; do
		obj=${src%.c}
		echo compiling...${obj}.c
		${CC} -o $obj ${obj}.c ${CFLAGS}
	done
}

# compile_all_implicitly $*

compile_explicitly()
{
    echo compiling example.c file ...
    gcc -o example example.c ${CFLAGS}
}

compile_explicitly 

#######################################################
## $1, $2,...: The parameters given to the script
## $*: A list of all the parameters given to the script

## Parameter Expansion 			Description
## ${param:-default} 			If param is null, then set it to the value of default.
## ${#param} 					Gives the length of param
## ${param%word} 				From the end, removes the smallest part of param that matches word and returns the rest
## ${param%%word} 				From the end, removes the longest part of param that matches word and returns the rest
## ${param#word} 				From the beginning, removes the smallest part of param that matches word and returns the rest
## ${param##word} 				From the beginning, removes the longest part of param that matches word and returns the rest
